---
title: "Exploring the patterns of and trait associated with freshwater invertebrate trends in the UK picOutput"
output: html_document
date: "2024-07-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Output

```{r}
dir.create("Figure")
dir.create("Data_export")
six_group<-read.csv("/Users/fuwenjie/Desktop/hypothesis1/traits/six_group.csv")
# Fig.1.1 hybrid line graph --------------------------------------------------------------------
data <- six_group
# trend
data$Year <- as.integer(data$Year)

# Selection of data from 1970 to 2015
filtered_data <- subset(data, Year >= 1970 & Year <= 2015)

# Calculate the average value for each Group for each year, sorted by year and Group
library(dplyr)
mean_values <- filtered_data %>%
  group_by(Year, Group) %>%
  summarise(mean_value = mean(Mean, na.rm = TRUE))

# library
library(ggplot2)
library(gridExtra)
# drawings
dev.off()
p <- ggplot(mean_values, aes(x = Year, y = mean_value, color = Group)) +
  geom_line(size = 1) + 
  labs(
    x = "Year",
    y = "Average Value",
    color = "Group"
  ) + 
  theme_classic() +
  theme(
    # Set the title to be horizontally centred, set the font size to 20, set the font to be bold
    axis.title.x = element_text(size = 14), 
    axis.title.y = element_text(size = 14), 
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14), 
    legend.text = element_text(size = 12), 
    plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), "inch"),
    panel.grid.major = element_line(color = "gray", size = 0.25),
    panel.border = element_rect(color = "black", fill = NA, size = 1)
  ) + 
  scale_y_continuous(
    limits = c(0.05, 0.3),
    breaks = c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3)
  ) +
  scale_x_continuous(
    limits = c(1970, 2015),
    breaks = c(1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015)
  ) +
  scale_color_brewer(palette = "Dark2") +
  geom_smooth(aes(group = 1), method = "gam", color = "black", linetype = "dashed", size = 1, se = TRUE) # Add total fit line

# can use RColorBrewer::display.brewer.all() to see the relevant colourways, reset the

print(p)
# save
ggsave("Figure/Average Value Trend by Group 3.pdf", plot = p, width = 10, height = 6)

# Fig.1.2 Single Group Line Chart ---------------------------------------------------------------------

# get only Group
groups <- unique(mean_values$Group)
print(groups)

colors <- c("#a09fa4", "#fea0a0", "#ad07e3", "#55a0fb", "#099a63", "#91bffa")

# creat every Group list
plots <- list()
for (i in 1:length(groups)) {
  group <- groups[i]
  group_data <- subset(mean_values, Group == group)
  p <- ggplot(group_data, aes(x = Year, y = mean_value)) +
    geom_line(size = 1, color = colors[i %% length(colors) + 1]) +
    labs(
      
      x = "Year",
      y = "Average Value"
    ) +
    theme_classic() +
    theme(
      
      axis.title.x = element_text(size = 12),
      axis.title.y = element_text(size = 12),
      axis.text = element_text(size = 10), 
      # panel.grid.major = element_line(color = "gray", size = 0.25),
      plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), "inch")
    ) +
    scale_y_continuous(
      limits = c(0.05, 0.3),
      breaks = c(0.05, 0.1, 0.15, 0.2, 0.25, 0.3)
    ) # This sets the scale of the uniform y-axis, which can be commented out if not needed.
  plots[[i]] <- p
}
grid.arrange(grobs = plots, ncol = 3)

ggsave("Figure/average value trend by groups 1.pdf", plot = grid.arrange(grobs = plots, ncol = 3), width = 10, height = 6)
```

```{r }
# Fig.2 heat map ---------------------------------------------------------------------
# Data Dealing
# EDA
load("/Users/fuwenjie/Desktop/hypothesis1/traits/final_completed.rdata")
library(corrplot)

# Select only numeric columns from the dataframe
numeric_columns <- final_completed[, c( "Mean_growth_rate", "N_Years", "N_Records", "acid.class", "focus.temp", "specificity", "toc")]

## 2.1  Setting the factorial ####
raw_data <- as.data.frame(numeric_columns)
ordata <- raw_data
colnames(ordata)
numdata <- ordata

## 2.2 Calculate the correlation matrix #####
M <- cor(numdata)
M
write.csv(M, "Data_export/orrelation matrix r value csv")

## 2.3 Significance test for correlation####
testRes <- cor.mtest(numdata, conf.level = 0.95)
testRes
write.csv(testRes, "Data_export/Correlation analysis p-value.csv")
par(mfrow = c(2, 3))

## 2.4 Correlation heat mapping####
dev.off()
pdf(file = "Figure/correlation_plot.pdf", width = 6, height = 6)
#  Plot the first corrplot layer, using circles to indicate correlation
corrplot(M,
  tl.col = "black",
  method = "circle"
)
# Immediately after that, add a second layer on top of the same graph, 
# using colour to indicate the strength of the correlation
corrplot(
  M,
  method = "color",
  type = "upper",
  add = TRUE,
  tl.pos = "n",
  cl.pos = "n",
  diag = FALSE,
  p.mat = testRes$p,
  sig.level = c(0.01, 0.05),
  pch.cex = 1.5,
  insig = "label_sig"
)


```

```{r}
# Fig.3 Forest map----------------------------------------------------------------
# for mean as y
## 3.1data processing####
load("/Users/fuwenjie/Desktop/hypothesis1/traits/final_completed.rdata")
final_completed <- final_completed[, !(names(final_completed) %in% "Precision")]

library(broom)

six_group1 <- six_group[, c(3, 5, 6)]
final_completed <- final_completed %>% rename("Year" = "First_Year")

final <- final_completed %>% left_join(six_group1, by = c("Species", "Year"))

# Select variables to include in the regression model
variables_to_plot <- c("acid.class", "focus.temp", "specificity", "toc")

# Fit the regression model
regression_formula <- as.formula(paste("Mean ~", paste(variables_to_plot, collapse = " + ")))
regression_model <- lm(regression_formula, data = final)

# Get the coefficients and confidence intervals
regression_results <- tidy(regression_model, conf.int = TRUE)
regression_results

# Filter results to include only the variables of interest
regression_results <- regression_results %>%
  filter(term %in% variables_to_plot)
write.csv(regression_results, "Data_export/regression_results.csv")
## 3.2 Plot####

# Create forest_plot dataframe
forest_plot <- regression_results %>%
  mutate(
    OR_mean = estimate,
    OR_low = conf.low,
    OR_up = conf.high
  )

library(forestplot)

pdf(file = "Figure/Regression Coefficients 3.pdf", width = 10, height = 6, onefile = FALSE) 

forestplot(
  mean = forest_plot$OR_mean, 
  lower = forest_plot$OR_low, 
  upper = forest_plot$OR_up, 
  labeltext = as.matrix(forest_plot[, 1:3]), ## Chart Title
  align = c("c", "c", "l"), 
  boxsize = 0.15, 
  zero = 0, 
  lineheight = unit(2, "cm"), 
  colgap = unit(1, "cm"), 
  lwd.zero = 3, 
  lwd.ci = 2, 
  grid = TRUE, 
  col = fpColors(box = "#4A6FE3", summary = "#8B008B", lines = "black", zero = "#D33F6A"), 
  lwd.xaxis = 2, 
  clip = c(-0.05, 0.02),
  xticks = c(-0.05, -0.04, -0.03, -0.02, -0.01, 0, 0.01, 0.02),
  txt_gp = fpTxtGp(
    label = gpar(cex = 1.25),
    ticks = gpar(cex = 1.1),
    xlab = gpar(cex = 1.2),
    title = gpar(cex = 2)
  ),
  lty.ci = "solid", # title = "Regression Coefficients and 95% Confidence Intervals", 
  xlab = "Estimate", 
  line.margin = 0.08,
  graph.pos = 2,
  mar = unit(rep(1.25, times = 4), "cm")
)

dev.off()
```
```{r}
# Fig.4 Trend scatterplot（mean）---------------------------------------------------------------
dir.create("Figure/M_trend")
library(ggExtra)
library(ggplot2)
library(patchwork)

variables_to_plot <- regression_results$term
plot_list <- list()

for (variable in variables_to_plot) {
  # Constructing models and extracting statistics
  model <- lm(Mean ~ get(variable), data = final)
  stats <- glance(model)
  p_value <- stats$p.value
 
  
  p <- ggplot(final, aes_string(x = variable, y = "Mean", color = "Group")) +
    geom_point(size = 1) +
    labs(
      
      x = paste(variable, "value"), y = "trend"
    ) +
    scale_color_manual(values = c(
      "AquaticBugs" = "#1f77b4",
      "Caddisflies" = "#ff7f0e",
      "Dragonflies" = "#2ca02c",
      "Mayflies" = "#d62728",
      "NonmarineMolluscs" = "#9467bd",
      "Stoneflies" = "#8c564b"
    )) +
    geom_smooth(method = "lm", color = "blue", fill = "blue", alpha = 0.2, se = T) +
    annotate("text", x = Inf, y = Inf, label = sprintf("p-Value = %.8f\n", p_value), hjust = 1.1, vjust = 1.1, size = 2.5) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    guides(color = guide_legend(override.aes = list(size = 4))) +
    theme_minimal(base_size = 14) +
    theme(
      plot.background = element_rect(fill = "white", color = "white"),
      plot.title = element_text(size = 12, hjust = 0.5, vjust = 0, ),
      plot.margin = unit(c(1, 1, 1, 1), "inch"),
      legend.title = element_blank(),
      legend.position = "bottom"
    )
  p4 <- ggMarginal(p,
    type = "densigram", alpha = 0.7,
    groupColour = TRUE, groupFill = TRUE,
    binwidth = 0.2,
  )
  p4

  plot_list[[variable]] <- p4
  ggsave(paste0("Figure/M_trend/plot_", variable, ".pdf"), plot = p4, width = 6, height = 4.5)
}
combined_plot <- wrap_plots(plot_list, ncol = 2)
ggsave("Figure/M_combined_trend.pdf", combined_plot,
  width = 12, height = 9
)

```

```{r}
# Building the linear model for focus.temp
lm_model1 <- lm(Mean ~ focus.temp, data = final)
summary(lm_model1)

# Building the linear model for specificity
lm_model2 <- lm(Mean ~ specificity, data = final)
summary(lm_model2)

# Open a PDF device
pdf("Diagnostic_Plots1.pdf", width = 8, height = 8)  # Set the size as needed

# Set up the plotting area
par(mfrow = c(2, 2),  # Layout: 2 rows and 2 columns
    mar = c(4, 4, 2, 1),  # Margins: bottom, left, top, right
    mgp = c(2, 0.5, 0),  # Margins for title, axis labels, and axis line
    cex = 0.8,  # Scaling of text (default is 1)
    las = 1)  # Orientation of axis labels: horizontal

# Generate diagnostic plots for lm_model1
plot(lm_model1,
     pch = 19,  # Type of point
     col = "#1f77b4",  # Color of points
     cex.lab = 1.2,  # Size of axis labels
     cex.axis = 1.1,  # Size of axis numbers
     cex.main = 1.4)  # Size of main title

# Close the PDF device
dev.off()
# Open a PDF device
pdf("Diagnostic_Plots2.pdf", width = 8, height = 8)  # Set the size as needed

# Set up the plotting area
par(mfrow = c(2, 2),  # Layout: 2 rows and 2 columns
    mar = c(4, 4, 2, 1),  # Margins: bottom, left, top, right
    mgp = c(2, 0.5, 0),  # Margins for title, axis labels, and axis line
    cex = 0.8,  # Scaling of text (default is 1)
    las = 1)  # Orientation of axis labels: horizontal

# Generate diagnostic plots for lm_model1
plot(lm_model2,
     pch = 19,  # Type of point
     col = "#1f77b4",  # Color of points
     cex.lab = 1.2,  # Size of axis labels
     cex.axis = 1.1,  # Size of axis numbers
     cex.main = 1.4)  # Size of main title

# Close the PDF device
dev.off()
```

```{r}
# FFig.5 Box plot (ANOVA analysis)---------------------------------------------------------------
## 5.1 acid.class####
# Converting variables to factors
final$acid.class <- as.factor(final$acid.class)

# Creating Linear Models
lm_model <- lm(Mean ~ acid.class, data = final)
summary(lm_model)

# ANOVA
anova_results <- anova(lm_model)
print(anova_results)

# Visualising results using box-and-line diagrams
p <- ggplot(final, aes(x = acid.class, y = Mean, color = Group)) +
  geom_boxplot(outlier.shape = 16, outlier.size = 2) +
  labs(
    
    x = "acid.class",
    y = "Mean"
  ) +
  geom_jitter(shape = 16, width = 0.2, size = 0.1, stroke = 2, alpha = 0.4) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
p2 <- p + scale_color_manual(values = c(
"AquaticBugs" = "#1f77b4",
      "Caddisflies" = "#ff7f0e",
      "Dragonflies" = "#2ca02c",
      "Mayflies" = "#d62728",
      "NonmarineMolluscs" = "#9467bd",
      "Stoneflies" = "#8c564b"
)) +
  theme(
        legend.position = "right", 
    legend.title = element_text(size = 14), 
    legend.text = element_text(size = 12), 
    plot.title = element_text(hjust = 0.5, size = 15),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)

  ) +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "inch"))

pdf("Figure/acid.classboxplot.pdf", width = 8, height = 6)
par(mar = c(5, 7, 7, 2) + 0.1, oma = c(0, 0, 2, 0))
print(p2)

dev.off()
# Results visualised using box-and-line diagrams-groups

p <- ggplot(final, aes(x = acid.class, y = Mean, color = acid.class)) +
  geom_boxplot(outlier.shape = 16, outlier.size = 2) +
  labs(
    x = "acid.class",
    y = "Mean"
  ) +
  geom_jitter(shape = 16, width = 0.2, size = 0.1, stroke = 2, alpha = 0.4) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
p2 <- p + scale_color_manual(values = c(
  "1" = "#1f77b4",
  "2" = "#ff7f0e",
  "3" = "#2ca02c",
  "4" = "#d62728",
  "5" = "#9467bd"
)) +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 14), 
    legend.text = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, size = 15),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)
  ) +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "inch"))

pdf("Figure/acid.classboxplot2.pdf", width = 8, height = 6)
par(mar = c(5, 7, 7, 2) + 0.1, oma = c(0, 0, 2, 0))
print(p2)

dev.off()
## 5.2 toc##### 
#Converting toc variables to factors
final$toc <- as.factor(final$toc)

# Creating Linear Models
lm_model <- lm(Mean ~ toc, data = final)
summary(lm_model)

# ANOVA
anova_results <- anova(lm_model)
print(anova_results)

# Visualising results using box-and-line diagrams
p <- ggplot(final, aes(x = toc, y = Mean, color = Group)) +
  geom_boxplot(outlier.shape = 16, outlier.size = 2) +
  labs(
    x = "toc",
    y = "Mean"
  ) +
  geom_jitter(shape = 16, width = 0.2, size = 0.1, stroke = 2, alpha = 0.4) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
p2 <- p + scale_color_manual(values = c(
"AquaticBugs" = "#1f77b4",
      "Caddisflies" = "#ff7f0e",
      "Dragonflies" = "#2ca02c",
      "Mayflies" = "#d62728",
      "NonmarineMolluscs" = "#9467bd",
      "Stoneflies" = "#8c564b"
)) +
  theme(
    legend.position = "right", 
    legend.title = element_text(size = 14), 
    legend.text = element_text(size = 12), 
    plot.title = element_text(hjust = 0.5, size = 15),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)
  ) +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "inch"))

pdf("Figure/toc boxplot.pdf", width = 8, height = 6)
par(mar = c(5, 7, 7, 2) + 0.1, oma = c(0, 0, 2, 0))
print(p2)

dev.off()

# Results visualised using box-and-line diagrams2-groups
p <- ggplot(final, aes(x = toc, y = Mean, color = toc)) +
  geom_boxplot(outlier.shape = 16, outlier.size = 2) +
  labs(
    x = "toc",
    y = "Mean"
  ) +
  geom_jitter(shape = 16, width = 0.2, size = 0.1, stroke = 2, alpha = 0.4) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw()
p2 <- p + scale_color_manual(values = c(
  "1" = "#1f77b4",
  "2" = "#ff7f0e",
  "3" = "#2ca02c",
  "4" = "#d62728",
  "5" = "#9467bd"
)) +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 14), 
    legend.text = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, size = 15),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)
  ) +
  theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "inch"))

pdf("Figure/toc boxplot2.pdf", width = 8, height = 6)
par(mar = c(5, 7, 7, 2) + 0.1, oma = c(0, 0, 2, 0))
print(p2)

dev.off()
```

